title: "Header"
status: "ready"
preview: "@preview-no-padding"
context:
    home: "#0"
    applicationTitle: "Application Title"
variants:
    - name: "id module"
      context:
          navigation: "true"
          identityModule: "true"
          user:
            initials: "rs"
            username: "rswanson"
          id: "id-module-simple"
    - name: "id module advanced"
      context:
          navigation: "true"
          identityModule: "true"
          user:
            initials: "rs"
            username: "rswanson"
          dropdown: "true"
          userFunctions:
            - link: "#"
              text: "Account settings"
            - link: "#"
              text: "Admin task one"
            - link: "#"
              text: "Admin task two"
          id: "identity-module"
    - name: "navigation"
      context:
          navigation: "true"
          main: "true"
          dropdown: "true"
          navItems:
            - link: "#"
              text: "Nav one"
            - text: "Nav two"
              id: "1"
              relatedLinks:
                - link: "#"
                  text: "Item one"
                - link: "#"
                  text: "Item two"
                - link: "#"
                  text: "Item three"
            - link: "#"
              text: "Nav three"
            - text: "Nav four"
              id: "2"
              relatedLinks:
                - link: "#"
                  text: "Item one"
                - link: "#"
                  text: "Item two"
                - link: "#"
                  text: "Item three"
                - link: "#"
                  text: "Item four"
          id: "navigation"
    - name: "navigation identity"
      context:
          navigation: "true"
          main: "true"
          identityModule: "true"
          user:
            initials: "rs"
            username: "rswanson"
          dropdown: "true"
          userFunctions:
            - link: "#"
              text: "Account settings"
            - link: "#"
              text: "Admin task one"
            - link: "#"
              text: "Admin task two"
          navItems:
            - link: "#"
              text: "Nav one"
            - text: "Nav two"
              id: "1"
              relatedLinks:
                - link: "#"
                  text: "Item one"
                - link: "#"
                  text: "Item two"
                - link: "#"
                  text: "Item three"
                - link: "#"
                  text: "Item four"
            - link: "#"
              text: "Nav three"
            - text: "Nav four"
              id: "2"
              relatedLinks:
                - link: "#"
                  text: "Item one"
                - link: "#"
                  text: "Item two"
                - link: "#"
                  text: "Item three"
                - link: "#"
                  text: "Item four"
          id: "navigation-identity"
    - name: "navigation simple identity"
      context:
          navigation: "true"
          main: "true"
          identityModule: "true"
          user:
            initials: "rs"
            username: "rswanson"
          navItems:
            - link: "#"
              text: "Nav one"
            - text: "Nav two"
              id: "1"
              relatedLinks:
                - link: "#"
                  text: "Item one"
                - link: "#"
                  text: "Item two"
                - link: "#"
                  text: "Item three"
                - link: "#"
                  text: "Item four"
            - link: "#"
              text: "Nav three"
            - text: "Nav four"
              id: "2"
              relatedLinks:
                - link: "#"
                  text: "Item one"
                - link: "#"
                  text: "Item two"
                - link: "#"
                  text: "Item three"
                - link: "#"
                  text: "Item four"
          id: "navigation-identity"
    - name: "persistent"
      context:
          persistent: "true"
          navigation: "true"
          main: "true"
          identityModule: "true"
          user:
            initials: "rs"
            username: "rswanson"
          dropdown: "true"
          userFunctions:
            - link: "#"
              text: "Account settings"
            - link: "#"
              text: "Admin task one"
            - link: "#"
              text: "Admin task two"
          navItems:
            - link: "#"
              text: "Nav one"
            - text: "Nav two"
              id: "1"
              relatedLinks:
                - link: "#"
                  text: "Item one"
                - link: "#"
                  text: "Item two"
                - link: "#"
                  text: "Item three"
                - link: "#"
                  text: "Item four"
            - link: "#"
              text: "Nav three"
            - text: "Nav four"
              id: "2"
              relatedLinks:
                - link: "#"
                  text: "Item one"
                - link: "#"
                  text: "Item two"
                - link: "#"
                  text: "Item three"
                - link: "#"
                  text: "Item four"
          id: "mobile-drawer"